[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src/"
testpaths = ["tests"]
python_files = "test_*.py"
doctest_optionflags = "NORMALIZE_WHITESPACE"

[tool.coverage.run]
omit = ["env/*", "tests/*", ".eggs/*"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = python3.6

[testenv]
deps = .[test]
whitelist_external = make
install_command = python -m pip install {opts} {packages}
commands =
    pytest
"""